## Listes

In [1]:
import numpy as np
liste = [1,2,3,4,5,6]
del liste[1]

In [2]:
print(liste)

[1, 3, 4, 5, 6]


In [3]:
liste.remove(5)
print(liste)

[1, 3, 4, 6]


In [4]:
liste1 = [1,2,3,4,5,6]
liste1.reverse()
print(liste1)

[6, 5, 4, 3, 2, 1]


In [5]:
liste2 = [1,2,3,4,5,6,3]
liste2.count(3)

2

In [6]:
liste2.index(5)

4

In [7]:
liste2[-4:]

[4, 5, 6, 3]

In [8]:
chaine = "Lycée Charles Carnus"
chaine.split(" ")

['Lycée', 'Charles', 'Carnus']

In [9]:
liste = ['Lycée', 'Charles', 'Carnus']
" ".join(liste)

'Lycée Charles Carnus'

In [10]:
x = [1, 2, 3, 4]
y = [10, 11, 12]
x.extend(y)
print(x)

[1, 2, 3, 4, 10, 11, 12]


In [11]:
a = [1, 2, 3, 4]
a.insert(1, 5)
print(a)

[1, 5, 2, 3, 4]


In [12]:
from itertools import permutations
list(permutations([1, 2, 3]))

[(1, 2, 3), (1, 3, 2), (2, 1, 3), (2, 3, 1), (3, 1, 2), (3, 2, 1)]

In [13]:
x = [1, 2, 3]
y = [4, 5, 6]
x + y

[1, 2, 3, 4, 5, 6]

In [14]:
x = [1, 2]
x*5

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [15]:
[0] * 4

[0, 0, 0, 0]

In [16]:
matrice1 = np.array(np.mat('1 2; 3 4'))
print(matrice1)

[[1 2]
 [3 4]]


In [17]:
matrice20 = np.matrix([[1, 2], [3, 4]])
print(matrice20)

[[1 2]
 [3 4]]


In [18]:
matrice2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrice2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print("Vecteur original :")
print(arr)

Vecteur original :
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [20]:
reshaped_arr = arr.reshape(3, 4)
print("Matrice résultante (3x4):")
print(reshaped_arr)

Matrice résultante (3x4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [21]:
import numpy as np

# matrice 2x3
matrice = np.array([[1, 2, 3], [4, 5, 6]])

resultat = matrice.flatten()
print("Résultat :", resultat)

Résultat : [1 2 3 4 5 6]


In [22]:
A = np.array([[1, 2, 3], [3, 4, 5]], dtype = complex)
print(A)

[[1.+0.j 2.+0.j 3.+0.j]
 [3.+0.j 4.+0.j 5.+0.j]]


In [23]:
import numpy as np

A = np.array([[1, 4, 5, 12],
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]])

print("A = ",A)

#  1er élément de la 1ère ligne
print("A[0][0] =", A[0][0])  

# 3ème élément de la 2ème ligne
print("A[1][2] =", A[1][2])

# Dernier élément de la dernière ligne
print("A[-1][-1] =", A[-1][-1])  

A =  [[ 1  4  5 12]
 [-5  8  9  0]
 [-6  7 11 19]]
A[0][0] = 1
A[1][2] = 9
A[-1][-1] = 19


In [24]:
import numpy as np

A = np.array([[1, 4, 5, 12], 
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]])

print("A[:,0] =",A[:,0]) # 1ère colonne
print("A[:,3] =", A[:,3]) # 4ème colonne
print("A[:,-1] =", A[:,-1]) # Dernière colonne (4ème colonne dans notre cas)

A[:,0] = [ 1 -5 -6]
A[:,3] = [12  0 19]
A[:,-1] = [12  0 19]


In [25]:
import numpy as np
vecteur = np.array([1, 3, 5, 7, 9, 7, 5])

print(vecteur[2:5])        # Sortie : [5, 7, 9]

print(vecteur[:-5])        # Sortie : [1, 3]   

print(vecteur[5:])         # Sortie :[7, 5]

print(vecteur[:])          # Sortie :[1, 3, 5, 7, 9, 7, 5]

print(vecteur[::-1])       # Sortie :[5, 7, 9, 7, 5, 3, 1]

[5 7 9]
[1 3]
[7 5]
[1 3 5 7 9 7 5]
[5 7 9 7 5 3 1]


In [26]:
import numpy as np

A = np.array([[1, 4, 5, 12, 14], 
    [-5, 8, 9, 0, 17],
    [-6, 7, 11, 19, 21]])

print(A)
''' Sortie :
[[ 1  4  5 12 14]
 [-5  8  9  0 17]
 [-6  7 11 19 21]]
'''

print(A[:2, :4])  # 2 lignes, 4 colonnes
''' Sortie :
[[ 1  4  5 12]
 [-5  8  9  0]]
'''

print(A[:1,])  # 1ère ligne, toutes les colonnes
''' Sortie :
[[ 1  4  5 12 14]]
'''

print(A[:,2])  # toutes les lignes, 2ème colonne
''' Sortie :
[ 5  9 11]
'''

print(A[:, 2:5])  # toutes les lignes, de la 3ème à la 5ème colonne
''' Sortie :
[[ 5 12 14]
 [ 9  0 17]
 [11 19 21]]
'''

[[ 1  4  5 12 14]
 [-5  8  9  0 17]
 [-6  7 11 19 21]]
[[ 1  4  5 12]
 [-5  8  9  0]]
[[ 1  4  5 12 14]]
[ 5  9 11]
[[ 5 12 14]
 [ 9  0 17]
 [11 19 21]]


' Sortie :\n[[ 5 12 14]\n [ 9  0 17]\n [11 19 21]]\n'

In [27]:
x = np.matrix(np.arange(12).reshape((3,4)))
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [28]:
import numpy as np

# Tableau (vecteur) de nombres aléatoires
a = np.random.randint(1, 5, 10)

print(a)

[4 3 4 2 3 4 3 4 1 4]


In [29]:
import numpy as np

np.random.seed(0)

x = np.random.rand(2,3)
print("Matrice x :")
print(x)

Matrice x :
[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]]


In [30]:
import numpy as np
# np.random.randint(low, high=None, size=None, dtype='l')

tab = np.random.randint(0,5,size = (3,4))
print(tab)

[[4 0 0 4]
 [2 1 0 1]
 [1 0 1 4]]


In [31]:
import numpy as np

tableau = np.random.randint(-5,5,size = (2,3))
print(tableau)

[[-2 -5 -2]
 [ 0 -5 -3]]


In [32]:
import numpy as np

tableau = np.random.randint(0,100,size = (8,7))
print(tableau)

[[99 88 49 29 19 19 14]
 [39 32 65  9 57 32 31]
 [74 23 35 75 55 28 34]
 [ 0  0 36 53  5 38 17]
 [79  4 42 58 31  1 65]
 [41 57 35 11 46 82 91]
 [ 0 14 99 53 12 42 84]
 [75 68  6 68 47  3 76]]
